# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefaircoin',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='usefaircoin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usefaircoin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='usefaircoin',
            name='name',
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='faircoin_adress',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='faircoin_address'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='lng',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='usefaircoin',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='usefaircoin',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
    ]
