# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190115_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefaircoin',
            old_name='faircoin_adress',
            new_name='faircoin_address',
        ),
    ]
