# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190115_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefaircoin',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
