# Generated by Django 2.0.13 on 2020-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_update_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ca', 'Catalan')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
