# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190930_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'ca', 'Catalan')], default=b'en', max_length=10, verbose_name='language'),
        ),
    ]
