# Generated by Django 2.0.13 on 2020-06-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valueaccounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateField(auto_now_add=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='valueaccounting.EconomicEvent')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='valueaccounting.EconomicAgent')),
            ],
            options={
                'ordering': ('validation_date',),
            },
        ),
    ]
