# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
