# Generated by Django 2.0.13 on 2020-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='email_address',
            field=models.EmailField(max_length=96, verbose_name='Email address'),
        ),
    ]
