# Generated by Django 2.0.13 on 2020-08-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200707_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='this join request became this EconomicAgent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_join_requests', to='valueaccounting.EconomicAgent', verbose_name='agent'),
        ),
    ]
