# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_joinrequest_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_artwork_type',
            new_name='general_artwork_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_material_type',
            new_name='general_material_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_nonmaterial_type',
            new_name='general_nonmaterial_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_unit_type',
            new_name='general_unit_type',
        ),
        migrations.RenameField(
            model_name='ocp_record_type',
            old_name='ocpRecordType_record_type',
            new_name='general_record_type',
        ),
        migrations.RenameField(
            model_name='ocp_skill_type',
            old_name='job',
            new_name='general_job',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_unit',
            new_name='general_unit',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_unit_type',
            new_name='general_unit_type',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_ocp_unit',
            new_name='ocp_unit',
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requested_username',
            field=models.CharField(help_text='If you have already an account in OCP, you can login before filling this form to have this project in the same account, or you can choose another username and email to have it separate.', max_length=32, verbose_name='Requested username'),
        ),
    ]
