# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0013_auto_20171106_1539'),
        ('work', '0033_auto_20171106_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_artwork_type',
            new_name='general_artwork_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='ocpArtworkType_unit_type',
            new_name='general_unit_type',
        ),
        migrations.RenameField(
            model_name='ocp_record_type',
            old_name='ocpRecordType_record_type',
            new_name='general_record_type',
        ),
        migrations.RenameField(
            model_name='ocp_skill_type',
            old_name='job',
            new_name='general_job',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_unit',
            new_name='general_unit',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_unit_type',
            new_name='general_unit_type',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocpUnitType_ocp_unit',
            new_name='ocp_unit',
        ),
        migrations.RemoveField(
            model_name='ocp_artwork_type',
            name='ocpArtworkType_material_type',
        ),
        migrations.RemoveField(
            model_name='ocp_artwork_type',
            name='ocpArtworkType_nonmaterial_type',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='exchange',
            field=models.OneToOneField(blank=True, help_text='this join request is linked to this Ocp Exchange', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='valueaccounting.Exchange', verbose_name='exchange'),
        ),
        migrations.AddField(
            model_name='ocp_artwork_type',
            name='rel_material_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Material Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_material', to='work.Ocp_Artwork_Type', verbose_name='related material_type'),
        ),
        migrations.AddField(
            model_name='ocp_artwork_type',
            name='rel_nonmaterial_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Non-material Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_nonmaterial', to='work.Ocp_Artwork_Type', verbose_name='related nonmaterial_type'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requested_username',
            field=models.CharField(help_text='If you have already an account in OCP, you can login before filling this form to have this project in the same account, or you can choose another username and email to have it separate.', max_length=32, verbose_name='Username *'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='ocp_artwork_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Artwork Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocp_skill_types', to='work.Ocp_Artwork_Type', verbose_name='general artwork_type'),
        ),
    ]
