# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0034_auto_20171109_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='exchange',
            field=models.OneToOneField(blank=True, help_text='this join request is linked to this Ocp Exchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request', to='valueaccounting.Exchange', verbose_name='exchange'),
        ),
    ]
