# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 22:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0034_auto_20170907_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocp_artwork_type',
            name='general_material_type',
        ),
        migrations.RemoveField(
            model_name='ocp_artwork_type',
            name='general_nonmaterial_type',
        ),
        migrations.AddField(
            model_name='ocp_artwork_type',
            name='rel_material_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Material Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_material', to='work.Ocp_Artwork_Type', verbose_name='related material_type'),
        ),
        migrations.AddField(
            model_name='ocp_artwork_type',
            name='rel_nonmaterial_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Non-material Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_nonmaterial', to='work.Ocp_Artwork_Type', verbose_name='related nonmaterial_type'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='ocp_artwork_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Artwork Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocp_skill_types', to='work.Ocp_Artwork_Type', verbose_name='general artwork_type'),
        ),
    ]
