# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 16:06


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0036_auto_20180704_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenumber',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_numbers', to='valueaccounting.Exchange', verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='this join request became this EconomicAgent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_join_requests', to='valueaccounting.EconomicAgent', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='skillsuggestion',
            name='resource_type',
            field=models.ForeignKey(blank=True, help_text='this skill suggestion became this ResourceType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_suggestions', to='valueaccounting.EconomicResourceType', verbose_name='resource_type'),
        ),
        migrations.AlterField(
            model_name='skillsuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_suggestion', to=settings.AUTH_USER_MODEL, verbose_name='suggested by'),
        ),
    ]
