# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0037_auto_20190226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_create_pass',
            field=models.BooleanField(default=False, verbose_name='auto create users'),
        ),
    ]
