# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-02 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0038_project_auto_create_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenumber',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_numbers_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='context_agent',
            field=models.ForeignKey(blank=True, help_text='a related OCP context EconomicAgent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_artwork_types', to='valueaccounting.EconomicAgent', verbose_name='context agent'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='facet',
            field=models.OneToOneField(blank=True, help_text='a related OCP Facet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_artwork_type', to='valueaccounting.Facet', verbose_name='ocp facet'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='facet_value',
            field=models.ForeignKey(blank=True, help_text='a related OCP FacetValue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_artwork_type', to='valueaccounting.FacetValue', verbose_name='ocp facet_value'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='general_unit_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Unit Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_artwork_types', to='general.Unit_Type', verbose_name='general unit_type'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='resource_type',
            field=models.OneToOneField(blank=True, help_text='a related OCP ResourceType', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_artwork_type', to='valueaccounting.EconomicResourceType', verbose_name='ocp resource_type'),
        ),
        migrations.AlterField(
            model_name='ocp_record_type',
            name='exchange_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_record_type', to='valueaccounting.ExchangeType', verbose_name='ocp exchange type'),
        ),
        migrations.AlterField(
            model_name='ocp_record_type',
            name='ocpRecordType_ocp_artwork_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Artwork Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_record_types', to='work.Ocp_Artwork_Type', verbose_name='general artwork_type'),
        ),
        migrations.AlterField(
            model_name='ocp_record_type',
            name='ocp_skill_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Skill Type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_record_types', to='work.Ocp_Skill_Type', verbose_name='general skill_type'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='facet',
            field=models.OneToOneField(blank=True, help_text='a related OCP Facet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_skill_type', to='valueaccounting.Facet', verbose_name='ocp facet'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='facet_value',
            field=models.OneToOneField(blank=True, help_text='a related OCP FacetValue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_skill_type', to='valueaccounting.FacetValue', verbose_name='ocp facet_value'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='resource_type',
            field=models.OneToOneField(blank=True, help_text='a related OCP ResourceType', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocp_skill_type', to='valueaccounting.EconomicResourceType', verbose_name='ocp resource_type'),
        ),
    ]
