# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0039_auto_20200202_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='joining_style',
            field=models.CharField(choices=[(b'subscription', 'subscription'), (b'shares', 'shares'), (b'moderated', 'moderated'), (b'autojoin', 'autojoin')], default=b'autojoin', max_length=12, verbose_name='joining style'),
        ),
    ]
