# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0020_economicresource_expiration_date'),
        ('work', '0040_auto_20200322_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocp_skill_type',
            name='event_type',
            field=models.OneToOneField(blank=True, help_text='a related OCP EventType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocp_skill_type', to='valueaccounting.EventType', verbose_name='ocp event_type'),
        ),
        migrations.AlterField(
            model_name='ocp_skill_type',
            name='ocp_artwork_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related Ocp Artwork Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocp_skill_types', to='work.Ocp_Artwork_Type', verbose_name='ocp artwork_type'),
        ),
    ]
