# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 00:26


from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0041_auto_20200402_1246'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocp_artwork_type',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ocp_record_type',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
