# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 17:31


from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0042_auto_20200526_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('declined', 'declined')], default='new', editable=False, max_length=12, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='type_of_user',
            field=models.CharField(choices=[('individual', 'individual'), ('collective', 'collective')], default='individual', help_text='* Required fields', max_length=12, verbose_name='Type of user'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('declined', 'declined')], default='new', editable=False, max_length=12, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='type_of_membership',
            field=models.CharField(choices=[('individual', 'individual membership (min 1 share)'), ('collective', 'collective membership (min 2 shares)')], default='individual', max_length=12, verbose_name='Type of membership'),
        ),
        migrations.AlterField(
            model_name='newfeature',
            name='screenshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photos', verbose_name='screenshot'),
        ),
        migrations.AlterField(
            model_name='project',
            name='joining_style',
            field=models.CharField(choices=[('subscription', 'subscription'), ('shares', 'shares'), ('moderated', 'moderated'), ('autojoin', 'autojoin')], default='autojoin', max_length=12, verbose_name='joining style'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_type_selection',
            field=models.CharField(choices=[('project', 'your project'), ('all', 'all platform')], default='all', max_length=12, verbose_name='resource type selection'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'private'), ('FCmembers', 'only FC members'), ('public', 'public')], default='FCmembers', max_length=12, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='skillsuggestion',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('declined', 'declined')], default='new', editable=False, max_length=12, verbose_name='state'),
        ),
    ]
