# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0042_auto_20200526_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='this join request became this EconomicAgent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_join_requests', to='valueaccounting.EconomicAgent', verbose_name='agent'),
        ),
    ]
