# Generated by Django 2.0.13 on 2020-06-19 01:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0043_auto_20200601_1731'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocp_artwork_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ocp_record_type',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='rel_material_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Material Type', limit_choices_to=work.models.Ocp_Artwork_Type.get_Q_material_type, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_material', to='work.Ocp_Artwork_Type', verbose_name='related material_type'),
        ),
        migrations.AlterField(
            model_name='ocp_artwork_type',
            name='rel_nonmaterial_type',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='a related General Non-material Type', limit_choices_to=work.models.Ocp_Artwork_Type.get_Q_nonmaterial_type, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_types_nonmaterial', to='work.Ocp_Artwork_Type', verbose_name='related nonmaterial_type'),
        ),
    ]
