# Generated by Django 2.0.13 on 2020-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentassociationtype',
            name='association_behavior',
            field=models.CharField(blank=True, choices=[('manager', 'manager'), ('custodian', 'custodian'), ('member', 'member'), ('child', 'child'), ('peer', 'peer'), ('supplier', 'supplier'), ('customer', 'customer')], max_length=12, null=True, verbose_name='association behavior'),
        ),
    ]
