# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 16:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0009_auto_20170422_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicevent',
            name='digital_currency_tx_state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('external', 'External'), ('error', 'Error')], max_length=12, null=True, verbose_name='digital currency transaction state'),
        ),
    ]
