# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0012_auto_20170717_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicresourcetype',
            name='behavior',
            field=models.CharField(choices=[('work', 'Type of Work'), ('account', 'Virtual Account'), ('dig_curr', 'Digital Currency'), ('dig_acct', 'Digital Currency Address'), ('dig_wallet', 'Digital Currency Wallet'), ('consumed', 'Produced/Changed + Consumed'), ('used', 'Produced/Changed + Used'), ('cited', 'Produced/Changed + Cited'), ('produced', 'Produced/Changed only'), ('other', 'Other')], default='other', max_length=12, verbose_name='behavior'),
        ),
    ]
