# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-18 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0013_auto_20180530_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='quantity',
            field=models.DecimalField(decimal_places=9, max_digits=20, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='economicevent',
            name='quantity',
            field=models.DecimalField(decimal_places=9, max_digits=20, verbose_name='quantity'),
        ),
    ]
