# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-02 12:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0014_auto_20191218_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='valueaccounting.Order', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='resourcetypelistelement',
            name='resource_type_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_elements', to='valueaccounting.ResourceTypeList', verbose_name='resource type list'),
        ),
    ]
