# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0017_auto_20200229_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassociationtype',
            name='inverse_label_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='inverse label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='inverse_label_en',
            field=models.CharField(max_length=40, null=True, verbose_name='inverse label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='inverse_label_es',
            field=models.CharField(max_length=40, null=True, verbose_name='inverse label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='label_ca',
            field=models.CharField(max_length=32, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='label_en',
            field=models.CharField(max_length=32, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='label_es',
            field=models.CharField(max_length=32, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='name_ca',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='plural_name_ca',
            field=models.CharField(default=b'', max_length=128, null=True, verbose_name='plural name'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='plural_name_en',
            field=models.CharField(default=b'', max_length=128, null=True, verbose_name='plural name'),
        ),
        migrations.AddField(
            model_name='agentassociationtype',
            name='plural_name_es',
            field=models.CharField(default=b'', max_length=128, null=True, verbose_name='plural name'),
        ),
        migrations.AddField(
            model_name='agentresourceroletype',
            name='name_ca',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='agentresourceroletype',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='agentresourceroletype',
            name='name_es',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
    ]
