# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0018_auto_20200314_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicresourcetype',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='economicresourcetype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='economicresourcetype',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='economicresourcetype',
            name='name_ca',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='economicresourcetype',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='economicresourcetype',
            name='name_es',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_ca',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_es',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
    ]
