# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 14:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0019_auto_20200316_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicresource',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
    ]
