# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-10 18:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0020_economicresource_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicagent',
            name='nick',
            field=models.CharField(help_text='Must be unique, and no more than 32 characters', max_length=32, unique=True, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='economicagent',
            name='nick_ca',
            field=models.CharField(help_text='Must be unique, and no more than 32 characters', max_length=32, null=True, unique=True, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='economicagent',
            name='nick_en',
            field=models.CharField(help_text='Must be unique, and no more than 32 characters', max_length=32, null=True, unique=True, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='economicagent',
            name='nick_es',
            field=models.CharField(help_text='Must be unique, and no more than 32 characters', max_length=32, null=True, unique=True, verbose_name='nick'),
        ),
    ]
