# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20171202_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rel_job_jobs',
            name='relation',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jo_job+', to='general.Relation'),
        ),
        migrations.AlterField(
            model_name='type',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='general.Type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ocp_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gen_unit', to='valueaccounting.Unit', verbose_name='OCP Unit'),
        ),
    ]
