# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-06 01:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20200202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='changed_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
