# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20200206_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='gerund_ca',
            field=models.CharField(blank=True, help_text='The verb in gerund, present', max_length=200, null=True, verbose_name='Gerund'),
        ),
        migrations.AddField(
            model_name='job',
            name='gerund_en',
            field=models.CharField(blank=True, help_text='The verb in gerund, present', max_length=200, null=True, verbose_name='Gerund'),
        ),
        migrations.AddField(
            model_name='job',
            name='gerund_es',
            field=models.CharField(blank=True, help_text='The verb in gerund, present', max_length=200, null=True, verbose_name='Gerund'),
        ),
        migrations.AddField(
            model_name='job',
            name='name_ca',
            field=models.CharField(help_text='The name of the Art', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='job',
            name='name_en',
            field=models.CharField(help_text='The name of the Art', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='job',
            name='name_es',
            field=models.CharField(help_text='The name of the Art', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='job',
            name='verb_ca',
            field=models.CharField(blank=True, help_text='The verb of the action, infinitive', max_length=200, null=True, verbose_name='Verb'),
        ),
        migrations.AddField(
            model_name='job',
            name='verb_en',
            field=models.CharField(blank=True, help_text='The verb of the action, infinitive', max_length=200, null=True, verbose_name='Verb'),
        ),
        migrations.AddField(
            model_name='job',
            name='verb_es',
            field=models.CharField(blank=True, help_text='The verb of the action, infinitive', max_length=200, null=True, verbose_name='Verb'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_ca',
            field=models.CharField(default=b'', help_text='The name of the Concept', max_length=200,
                                   null=True,
                                   unique=True,
                                   verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_en',
            field=models.CharField(default=b'', help_text='The name of the Concept', max_length=200,
                                   null=True,
                                   unique=True,
                                   verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_es',
            field=models.CharField(default=b'', help_text='The name of the Concept', max_length=200,
                                   null=True,
                                   unique=True,
                                   verbose_name='Name'),
        ),
    ]
