# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 17:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20200526_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', help_text='The name of the Concept', max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_ca',
            field=models.CharField(default='', help_text='The name of the Concept', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_en',
            field=models.CharField(default='', help_text='The name of the Concept', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_es',
            field=models.CharField(default='', help_text='The name of the Concept', max_length=200, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
