# Generated by Django 2.0.13 on 2020-06-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20200601_1731'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='company_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='material_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='nonmaterial_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='record_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='region_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='unit_type',
            managers=[
            ],
        ),
    ]
