# Generated by Django 2.0.13 on 2020-06-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valueaccounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(editable=False, max_length=96, verbose_name='Transaction Hash')),
                ('from_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='From Address')),
                ('to_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='To Address')),
                ('tx_fee', models.DecimalField(decimal_places=9, default=0, max_digits=20, verbose_name='Transaction Fee')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain_transaction', to='valueaccounting.EconomicEvent', verbose_name='event')),
            ],
        ),
        migrations.CreateModel(
            name='MulticurrencyAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.CharField(editable=False, max_length=100)),
                ('access_key', models.CharField(editable=False, max_length=100)),
                ('access_secret', models.CharField(editable=False, max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueaccounting.EconomicAgent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultiwalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(editable=False, max_length=96, verbose_name='Multiwallet Transaction ID')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Status')),
                ('sent_to', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sent to username')),
                ('method', models.CharField(blank=True, max_length=128, null=True, verbose_name='Method')),
                ('tx_fee', models.DecimalField(decimal_places=9, default=0, max_digits=20, verbose_name='Transaction Fee')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiwallet_transaction', to='valueaccounting.EconomicEvent', verbose_name='event')),
            ],
        ),
    ]
