# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0015_auto_20200202_1251'),
        ('multicurrency', '0002_blockchaintransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiwalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(editable=False, max_length=96, verbose_name='Multiwallet Transaction ID')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Status')),
                ('sent_to', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sent to username')),
                ('method', models.CharField(blank=True, max_length=128, null=True, verbose_name='Method')),
                ('tx_fee', models.DecimalField(decimal_places=9, default=0, max_digits=20, verbose_name='Transaction Fee')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiwallet_transaction', to='valueaccounting.EconomicEvent', verbose_name='event')),
            ],
        ),
    ]
