# Generated by Django 2.0.13 on 2020-06-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valueaccounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaircoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(editable=False, max_length=96, verbose_name='faircoin address')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faircoin_address', to='valueaccounting.EconomicResource', verbose_name='resource')),
            ],
        ),
        migrations.CreateModel(
            name='FaircoinTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, editable=False, max_length=96, null=True, verbose_name='Faircoin Transaction Hash')),
                ('tx_state', models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('external', 'External'), ('error', 'Error')], max_length=12, null=True, verbose_name='Faircoin Transaction State')),
                ('to_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='To Address')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Quantity')),
                ('minus_fee', models.BooleanField(default=False, verbose_name='Substract fee to total')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faircoin_transaction', to='valueaccounting.EconomicEvent', verbose_name='event')),
            ],
        ),
    ]
