# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faircoin', '0002_auto_20170708_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='faircointransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='faircointransaction',
            name='minus_fee',
            field=models.BooleanField(default=False, verbose_name='Substract fee to total'),
        ),
        migrations.AlterField(
            model_name='faircointransaction',
            name='to_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='To Address'),
        ),
        migrations.AlterField(
            model_name='faircointransaction',
            name='tx_hash',
            field=models.CharField(blank=True, editable=False, max_length=96, null=True, verbose_name='Faircoin Transaction Hash'),
        ),
        migrations.AlterField(
            model_name='faircointransaction',
            name='tx_state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('external', 'External'), ('error', 'Error')], max_length=12, null=True, verbose_name='Faircoin Transaction State'),
        ),
    ]
